Fix the name of cmake file
Fixes the following error:
```
Provides: s2n-tls-libs = 1.3.2-3.20221103104429906894.main.fc38 s2n-tls-libs(x86-64) = 1.3.2-3.20221103104429906894.main.fc38
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: libs2n.so.1()(64bit)
Processing files: s2n-tls-devel-1.3.2-3.20221103104429906894.main.fc38.x86_64
error: File not found: /builddir/build/BUILDROOT/s2n-tls-1.3.2-3.20221103104429906894.main.fc38.x86_64/usr/lib64/s2n/cmake/modules/FindLibCrypto.cmake
```

Signed-off-by: Frantisek Lachman <flachman@redhat.com>